[Distribution]
Distribution=arch

[Config]
Profiles=desktop,gnome,obs

[Content]
Packages=
        chezmoi
        git
        git-delta
        github-cli
        jujutsu
        fish
        starship
        atuin
        zoxide
        fzf
        vim
        helix
        yazi
        lazygit
        bat
        eza
        fd
        ripgrep
        xh
        tealdeer
        mise
        tailscale
        wl-clipboard
        parallel
        jq
        p7zip
        ffmpeg
        imagemagick
        poppler
        podman
        flatpak
        keyd
        ghostty
