[Distribution]
Distribution=arch

[Config]
Profiles=desktop,gnome,obs

[Content]
Packages=
        podman
        mkosi
        fish
        helix
        jujutsu
        git
        git-delta
        keyd
        xh
        github-cli
        tailscale
        lazygit
        zoxide
        fzf
        yazi
        starship
        bat
        atuin
        eza
        tealdeer
        mise
        ffmpeg
        p7zip
        jq
        poppler
        xh
        fd
        ripgrep
        imagemagick
        wl-clipboard
        parallel
        flatpak
